version: 2.1

jobs:
  
  test:
    working_directory: ~/commission7
    docker:
      - image: "circleci"
    steps:
      - checkout
      - run: ./commissioning.sh

workflows:
  test:
    jobs: 
      - test
  
          